### ISSUE TITLE
convert 方法错误, 里面第二个要用Encoder

### ISSUE THREAD

**Issue by ayanmw** [fesiong/goproject#1]
"github.com/axgle/mahonia"

这个库挺好的, 很简单，了解编码就可以自行扩展了。

貌似 mahonia （不知道为什么叫这种名字） 上面有个issue 就是你提的吧，Decoder的 ConvertString  方法总是转换成UTF8 ，所以你的第二个 decoder 没报错，但是如果转换成非UTF8 编码， 必会乱码。

**Comment by fesiong** [comment]
谢谢提醒

**Comment by fesiong** [comment]
已修正
